AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  The API and Lambda function for the AI Assistant to respond to SMS messages

Parameters:
  Environment:
    Type: String
  SuperpoweredModelId:
    Type: String
  TwilioPhoneNumber:
    Type: String
  AiName:
    Type: String
    Default: Alfred
  TwilioAccountSidParamName:
    Type: String
  TwilioAuthTokenParamName:
    Type: String
  SpApiKeyIdParamName:
    Type: String
  SpApiKeySecretParamName:
    Type: String
  

Globals:
  Function:
    Runtime: python3.9
    Timeout: 29


Resources:
  #######################################
  # API 
  #######################################
  ReceiveWebhooksApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: API for receiving webhooks from Twilio
      StageName: !Ref Environment

  #######################################
  # RESPOND TO SMS LAMBDA
  #######################################
  RespondToSmsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Description: Lambda function to respond to incoming SMS messages
      Handler: respond.lambda_handler
      CodeUri: src/incoming_sms_handler/
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID_PARAM_NAME: !Ref TwilioAccountSidParamName
          TWILIO_AUTH_TOKEN_PARAM_NAME: !Ref TwilioAuthTokenParamName
          PHONE_NUMBER_TO_INSTANCE_ID_MAP_TABLE_NAME: !Ref PhoneNumberToInstanceIdMap
          SP_MODEL_ID: !Ref SuperpoweredModelId
          SP_API_KEY_ID_PARAM_NAME: !Ref SpApiKeyIdParamName
          SP_API_KEY_SECRET_PARAM_NAME: !Ref SpApiKeySecretParamName
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /respond
            # Method should match the TwilioWebhookConfiguration "HttpMethod"
            Method: POST
            RestApiId: !Ref ReceiveWebhooksApi
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PhoneNumberToInstanceIdMap
        - DynamoDBWritePolicy:
            TableName: !Ref PhoneNumberToInstanceIdMap
        - SSMParameterReadPolicy:
            ParameterName: !Ref TwilioAccountSidParamName
        - SSMParameterReadPolicy:
            ParameterName: !Ref TwilioAuthTokenParamName
        - SSMParameterReadPolicy:
            ParameterName: !Ref SpApiKeyIdParamName
        - SSMParameterReadPolicy:
            ParameterName: !Ref SpApiKeySecretParamName

  #######################################
  # PHONE NUMBER TO INSTANCE_ID MAP 
  #######################################
  PhoneNumberToInstanceIdMap:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: phone_number
        Type: String

  #######################################
  # TWILIO WEBHOOK CONFIG CUSTOM RESOURCE 
  #######################################
  TwilioCustomResourceHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create_webhook_configuration.lambda_handler
      CodeUri: src/create_webhook_configuration/
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID_PARAM_NAME: !Ref TwilioAccountSidParamName
          TWILIO_AUTH_TOKEN_PARAM_NAME: !Ref TwilioAuthTokenParamName
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Ref TwilioAccountSidParamName
        - SSMParameterReadPolicy:
            ParameterName: !Ref TwilioAuthTokenParamName

  TwilioWebhookConfiguration:
    Type: Custom::TwilioWebhookConfiguration
    Properties:
      ServiceToken: !GetAtt TwilioCustomResourceHandler.Arn
      WebhookUrl: !Sub "https://${ReceiveWebhooksApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/respond"
      TwilioPhoneNumber: !Ref TwilioPhoneNumber
